<?php
class BTypes{
    const YENI_TEKNIK_RESIM_CIZ = "YENİ TEKNİK RESİM ÇİZ";
    const MEVCUT_TEKNIK_RESMI_REVIZE_ET = "MEVCUT TEKNİK RESMİ REVİZE ET";

    const TEKNIK_RESIM = "TEKNİK RESİM";
    const REFERANS_DOSYA = "REFERANS DOSYA";
    //const GUNCEL_DEGIL = "VAR";
    //const GUNCEL = "VAR";
    const YOK = "YOK";
    const UYGUN_DEGIL = "UYGUN DEĞİL";
    const UYGUN = "UYGUN";
    const ISLEMDE = "İŞLEMDE";
}

class SituationTypes{
    const REFERANS_TALEBI_DEGERLENDIRILIYOR = "REFERANS_TALEBI_DEGERLENDIRILIYOR";
    const REDDEDILDI = "REDDEDILDI";
    const ONAYLANDI = "ONAYLANDI";
    const ONAY_BEKLIYOR = "ONAY BEKLİYOR";
    const YENIDEN_ONAY_BEKLIYOR = "YENİDEN ONAY BEKLİYOR";
    const YENI_YUKLENDI = "YENİ YÜKLENDİ";
}

class ListTypes{
    const REFERANS_TALEBI = "REFERANS_TALEBI";
    const RUTIN_REVIZE_ISLEMI_TALEBI = "RUTIN_REVIZE_ISLEMI_TALEBI";
}